ROOT_DIR=$(cd $(dirname "$0")/..; pwd)

WORKDIR=${ROOT_DIR}/RUN
FORDIR=${ROOT_DIR}/RUN
SCRIPTDIR=${ROOT_DIR}/Scripts
RUNDIR=${ROOT_DIR}/OBS
EXECDIR=${ROOT_DIR}/WKB_MODEL
OBSDIR=${ROOT_DIR}/DATA
ASSIMDIR=${ROOT_DIR}/ASSIM
CASEDIR='mem'

OBSTYPES="OCG EPB"
exec='wkb.exe'
ENSSIZE=100
ID_BEG=1



